# Tarea 3
## Física Computacional
### Hernández Ramos Sandra 
$Sandii\hbar ers^{\heartsuit}$ 🦆🌵🌹🥀🌿🍀🌺🌷



## Julia

In [2]:
#import Pkg
#Pkg.add("Plots")
#Pkg.add("PyPlot")
using Plots
using LaTeXStrings
import PyPlot


┌ Info: Precompiling Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]
└ @ Base loading.jl:1192


Deps path: C:\Users\x\.julia\packages\FFMPEG\guN1x\src\..\deps\deps.jl


ERROR: LoadError: FFMPEG not installed properly, run `] build FFMPEG`, restart Julia and try again
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] top-level scope at C:\Users\x\.julia\packages\FFMPEG\guN1x\src\FFMPEG.jl:23
 [3] include at .\boot.jl:317 [inlined]
 [4] include_relative(::Module, ::String) at .\loading.jl:1044
 [5] include(::Module, ::String) at .\sysimg.jl:29
 [6] top-level scope at none:2
 [7] eval at .\boot.jl:319 [inlined]
 [8] eval(::Expr) at .\client.jl:393
 [9] top-level scope at .\none:3
in expression starting at C:\Users\x\.julia\packages\FFMPEG\guN1x\src\FFMPEG.jl:21
ERROR: LoadError: Failed to precompile FFMPEG [c87230d0-a227-11e9-1b43-d7ebe4e7570a] to C:\Users\x\.julia\compiled\v1.0\FFMPEG\TGvga.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1203
 [3] _require(::Base.PkgId) at .\loading.jl:960
 [4] require(::Base.PkgId) at .\loading.jl:858
 [5] require(::Module, ::Symbol) at .\loading.jl:8

ErrorException: Failed to precompile Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80] to C:\Users\x\.julia\compiled\v1.0\Plots\ld3vC.ji.

In [5]:
import Pkg
Pkg.add("Plots")

 Resolving package versions...
  Updating `C:\Users\x\.julia\environments\v1.0\Project.toml`
 [no changes]
  Updating `C:\Users\x\.julia\environments\v1.0\Manifest.toml`
 [no changes]


In [6]:
import Plots

┌ Info: Precompiling Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]
└ @ Base loading.jl:1192


Deps path: C:\Users\x\.julia\packages\FFMPEG\guN1x\src\..\deps\deps.jl


ERROR: LoadError: FFMPEG not installed properly, run `] build FFMPEG`, restart Julia and try again
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] top-level scope at C:\Users\x\.julia\packages\FFMPEG\guN1x\src\FFMPEG.jl:23
 [3] include at .\boot.jl:317 [inlined]
 [4] include_relative(::Module, ::String) at .\loading.jl:1044
 [5] include(::Module, ::String) at .\sysimg.jl:29
 [6] top-level scope at none:2
 [7] eval at .\boot.jl:319 [inlined]
 [8] eval(::Expr) at .\client.jl:393
 [9] top-level scope at .\none:3
in expression starting at C:\Users\x\.julia\packages\FFMPEG\guN1x\src\FFMPEG.jl:21
ERROR: LoadError: Failed to precompile FFMPEG [c87230d0-a227-11e9-1b43-d7ebe4e7570a] to C:\Users\x\.julia\compiled\v1.0\FFMPEG\TGvga.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1203
 [3] _require(::Base.PkgId) at .\loading.jl:960
 [4] require(::Base.PkgId) at .\loading.jl:858
 [5] require(::Module, ::Symbol) at .\loading.jl:8

ErrorException: Failed to precompile Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80] to C:\Users\x\.julia\compiled\v1.0\Plots\ld3vC.ji.

Resuelva los siguientes ejercicios, explicando claramente su razonamiento

<span style="color:blue">1. En clase vimos el método de Euler mejorado en el que nosotros introducimos el Jacobiano de forma
analítica para ser evaluado por el método de integración. Realice una función que implemente el
mismo método de integración, pero en lugar de calcular el Jacobiano con una función que lo evalúa
analíticamente, ahora sea calculado de manera numérica utilizando la derivación numérica<span>

Obtenemos una función que nos la función que nos exprese el jacobiano por lo que tomaremos en cuenta que la derivada parcial de una función será aumentando en la variable respecto a la cual derivaremos, el aumento esta dado por:
$$\frac{\partial f(\vec{x}_0)}{\partial x_i}=\frac{f(\vec{x}_0+h\vec{e_i})-f(f(\vec{x}_0-h\vec{e_i})}{2h}$$

Para el jacobiano usaremos la derivada parcial de la j-ésima entrada del jacobiano, así que usando la ecuación anterior tenemos: 
$$\frac{\partial f(\vec{x}_0)_j}{\partial x_i}=\frac{f(\vec{x}_0+h\vec{e_i})_j-f(f(\vec{x}_0-h\vec{e_i})_j}{2h}$$

In [10]:
#Definimos la función que nos dará la matriz jacobiana
#la entrada xi consiste en las variables espaciales del problema, donde obtendremos las parciales
#h el paso para la obtención de las derivadas parciales
#func es la función a la cual sacaremos el jacobiano
#t el tiempo donde evaluaremos la parcial temporal
function jacobianotemp(xi,h,funcion,t) #donde "xi" son las variables espaciales y ahí obtendremos las parciales, "h" los pasos para
                                    #obtener las derivadas parciales, "funcion" es la función a la que calcularemos el jacobiano
                                    # "t" es el tiempo donde se va a evaluar la parcial.
    #Entradas de la matriz:
    jac=zeros(length(funcion(xi,t)),length(xi)+1)
    #Ciclo for para guardar las entradas de la matriz
    for i in 1:length(funcion(xi,t)), j in 1:length(xi)
       #Vectores xp1 y xp2, como los vectores que tiene un aumento o desaumento en la i-ésima entrda.
        xp1=zeros(length(xi))
        xp2=zeros(length(xi))
        #Ciclo for para definir las entradas de los vectores donde se evaluará la función para obtener la derivada parcial
        for k in 1:length(xi)
            #Aqui sólo agregamos el incremento a la j-ésima entrada del vector
            if  k==j 
                xp1[k]=xi[j]+h
                xp2[k]=xi[j]-h
            else
                #Dejamos todas las demás entradas igual
                xp1[k]=xi[j]
                xp2[k]=xi[j]
            end
        end
        #Definimos la entrada ij de la matriz jacobiana, sin tomar en cuenta la entrada de la parcial temporal
        jac[i,j]=(funcion(xp1,t)[i]-funcion(xp2,t)[i])/(xp1[j]-xp2[j])
        #definimos las componentes de la columna de la parcial temporal
        jac[i,length(xi)+1]=(funcion(xi,t+h)[i]-funcion(xi,t-h)[i])/(2h)
    end
    return jac
end

jacobianotemp (generic function with 1 method)

Usamos la función del Notebook 9 "function Euler_mejorado_J_t" porque toma la posibilidad de que el sistema no sea autónomo y tenemos al jacobiano con dependencia temporal

In [11]:
#modificando un poco la función del Notebook 9
function Euler_mejorado_J_t_num(edo,edo_1,p_ini,t) #donde edo=función que nos da la ecuación diferencial ordinaria, edo_1=función,
    # J y g con dependencia temporal.           # con un elemento 1 en la última entrada, ejemplo [x,y,z,elemento]
    sol = zeros(length(t),length(p_ini))        #p_ini=condiciones de posición inicial, t=tiempo
    sol[1,:] = p_ini
    δ = t[2]-t[1]
    for i in 1:(length(t)-1)
        eval_edo = edo(sol[i,:],t[i])
        #definimos g* que es la función por la que multiplicaremos el jacobiano
        g=edo_1(sol[i,:],t[i])
        if length(eval_edo) == length(p_ini)
            sol[i+1,:] .= sol[i,:] .+ δ .*eval_edo
        else
            sol[i+1,:] .= sol[i,:] .+ δ .*eval_edo[1:(end-1)]
        end
        #cambiamos jacob por nuestra función del jacobiano que obtuvimos
        sol[i+1,:] .+= 0.5*(δ^2) .*(jacobianotemp(sol[i,:],δ,edo,t[i]) *g )
    end
    return sol
end

Euler_mejorado_J_t_num (generic function with 1 method)

Usamos el sitema de ecuaciones diferenciales del ejercicio 2 para comprobar que funciona la función

In [12]:
#Definimos a la función "sistema_t" con el sistma de ecuaciones
function sistema_t(xyz,t)
    # xyz = [x1, x2, x3]
    dx = xyz[2]
    dy = xyz[3]
    dz = -xyz[3]*xyz[3] + 3*xyz[2]*xyz[2]*xyz[2] - cos(xyz[1])*cos(xyz[1]) + exp(-1*t)*sin(3*t)
    return [dx,dy,dz]
end

sistema_t (generic function with 1 method)

Usaremos otra función que nos servirá de auxiliar muy parecida a "sistema_t" pero con una segunda entrada unitaria para obtener g*

In [13]:
function sistema_t_auxiliar(xyz,t)
    # xyz = [x1, x2, x3]
    dx = xyz[2]
    dy = xyz[3]
    dz = -xyz[3]*xyz[3] + 3*xyz[2]*xyz[2]*xyz[2] - cos(xyz[1])*cos(xyz[1]) + exp(-1*t)*sin(3*t)
    return [dx,dy,dz,1.0]
end
    

sistema_t_auxiliar (generic function with 1 method)

In [14]:
#Definimos "tiempo" que será el tiempo donde vamos a evaluar
tiempo = collect(1:0.1:1.5)
solucion = Euler_mejorado_J_t_num(sistema_t,sistema_t_auxiliar,[1.0,2.0,1.0],tiempo)

6×3 Array{Float64,2}:
 1.0      2.0       1.0    
 1.205    2.2138    3.23192
 1.44254  2.64661   5.43167
 1.73436  3.31959   8.33056
 2.10797  4.35329  13.1254 
 2.60893  6.03956  21.9648 

### ¡Funciona! 😁🎉

<span style="color:blue">2. Utilizando los integradores de Euler mejorado con Jacobiano analítico, Euler mejorado con Jacobiano
numérico, Runge-Kutta de $2^{\circ}$ orden y Runge-Kutta de $4^{\circ}$ orden, encuentre un paso de integración que
proporcione una precisión de $10^{−4}$
en la solución para la siguiente ecuación:
    \begin{equation}
\dddot{y}+\ddot{y}^{2}-3\dot{y}+\cos^{2}y=e^{-t}\sin(3t)
    \end{equation}
    
<span style="color:blue">Con condiciones iniciales $\ddot{y}(1) = 1$, $\dot{y}(1) = 2$, $y(1) = 1$. En particular que sucede en el intervalo $t \in [1, 2]$ y $t \in [1, 2.1]$.<span>

Usamos la función del Notebook 9 "Euler_mejorado_J_t" 

In [15]:
#Copiamos tal cual esta en el Notebook 9 😅
function Euler_mejorado_J_t(edo,p_ini,t,jacob)
    # J y g con dependencia temporal.
    sol = zeros(length(t),length(p_ini))
    sol[1,:] = p_ini
    δ = t[2]-t[1]
    for i in 1:(length(t)-1)
        eval_edo = edo(sol[i,:],t[i])
        if length(eval_edo) == length(p_ini)
            sol[i+1,:] .= sol[i,:] .+ δ .*eval_edo
        else
            sol[i+1,:] .= sol[i,:] .+ δ .*eval_edo[1:(end-1)]
        end
        sol[i+1,:] .+= 0.5*(δ^2) .*(jacob(sol[i,:],t[i]) *eval_edo )
    end
    return sol
end

Euler_mejorado_J_t (generic function with 1 method)

Usamos la función "RK_2" para el Método de Runge-Kutta de segundo orden (Notebook 10)

In [16]:
#Copiamos tal cual esta en el Notebook 10 😅
function RK_2(edo,x_ini,t)
    sol = zeros( length(t) , length(x_ini) )
    sol[1,:] .= x_ini
    δ = t[2]-t[1]
    for i in 1:length(t)-1
        k1 = sol[i,:] .+ 0.5*δ .*edo(sol[i,:],t[i])
        sol[i+1,:] .= sol[i,:] .+ δ*edo(k1,t[i]+0.5*δ)
    end
    return sol
end

RK_2 (generic function with 1 method)

Usamos la función "RK_4" para el Método de Runge-Kutta de cuarto orden (Notebook 10)(Notebook 11)

In [5]:
function RK_4(edo,x_ini,t)
    sol = zeros( length(t) , length(x_ini) )
    sol[1,:] .= x_ini
    δ = t[2]-t[1]
    for i in 1:length(t)-1
        k1 = edo(sol[i,:],t[i])
        k2 = edo(sol[i,:] .+ 0.5*δ.*k1 , t[i] + 0.5*δ)
        k3 = edo(sol[i,:] .+ 0.5*δ.*k2 , t[i] + 0.5*δ)
        k4 = edo(sol[i,:] .+ δ.*k2 , t[i] + δ)
        sol[i+1,:] .= sol[i,:] .+ (δ/6.0).*(k1 .+ 2.0.*k2 .+ 2.0.*k3 .+ k4)
    end
    return sol
end

RK_4 (generic function with 1 method)

Si reescribimos la cuación diferencial en un sistema de ecuaciones tenemos:
$$
x_1=y\\
\dot{x}_1 = x_2\\
\dot{x}_2 = x_3\\
\dot{x}_3 = -x_3^2 + 3x_2^3 - \cos^2{(x_1)} + e^{-t}\sin{(3t)}
$$
Con condiciones iniciales: $x_1(1)=1$, $x_2(1)=2$ y $x_3(1)=1$.

El Jacobiano para el sistema anterior es:
$$J^{*}=\begin{pmatrix}
0 & 1 & 0&0\\
0 & 0 & 1&0\\
2\sin(x_1)\cos(x_1) & 9x_2^{2} & -2x_3&3e^{-t}\cos(3t)-e^{-t}\sin(3t)
\end{pmatrix}$$

Definimos una función con el sistema de ecuaciones "EDO_1"

In [18]:
function EDO_1(vec,t)
    # donde "vec = [x1, x2, x3]"
    dx1 = vec[2]
    dx2 = vec[3]
    dx3 = -vec[3]*vec[3] + 3*vec[2]*vec[2]*vec[2] - cos(vec[1])*cos(vec[1]) + exp(-t)*sin(3*t)
    return [dx1,dx2,dx3]
end

EDO_1 (generic function with 1 method)

Definimos la función "EDO_1aumentada" que es muy similar a la anterior solo que se aumenta "1.0" en la última entrada

In [19]:
function EDO_1aumentada(vec,t)
    # donde "vec = [x1, x2, x3]"
    dx1 = vec[2]
    dx2 = vec[3]
    dx3 = -vec[3]*vec[3] + 3*vec[2]*vec[2]*vec[2] - cos(vec[1])*cos(vec[1]) + exp(-t)*sin(3*t)
    return [dx1,dx2,dx3,1.0]
end

EDO_1aumentada (generic function with 1 method)

Definimos una funcion para su Jacobiano Analítco "EDO_1_Jacobiano"

In [20]:
function EDO_1_Jacobiano(vec,t)
    # donde "vec = [x1, x2, x3]"
    J = zeros(3,4)
    J[1,2] = 1.0
    J[2,3] = 1.0
    J[3,1] = 2*cos(vec[1])*sin(vec[1])
    J[3,2] = 9*vec[2]*vec[2]
    J[3,3] = -2*vec[3]
    J[3,4] = 3*exp(-1*t)*cos(3*t)-exp(-1*t)*sin(3*t)
    return J
end

EDO_1_Jacobiano (generic function with 1 method)

Utilizaremos los diferentes métodos de integración para encontrar un paso de integración que proporcione una precisión de $10^{−4}$ en el intervalo $t \in [1, 2]$ 

#### <span style="color:green">Para Euler mejorado con Jacobiano analítico<span>

<span style="color:magenta"> Intervalo $t \in [1, 1.8]$ <span>

In [21]:
#Método de Euler con Jacobiano analítico
tEulerAnalitico = collect(1:0.001:1.8) #paso (0.001) para al menos 4 cifras significativas de t[1,1.8]
solEulerAnalitico= Euler_mejorado_J_t(EDO_1aumentada,[1.0,2.0,1.0],tEulerAnalitico,EDO_1_Jacobiano)

801×3 Array{Float64,2}:
 1.0       2.0        1.0    
 1.002     2.00101    1.02276
 1.004     2.00205    1.0455 
 1.006     2.0031     1.06824
 1.00801   2.00418    1.09097
 1.01001   2.00528    1.11369
 1.01202   2.00641    1.1364 
 1.01403   2.00756    1.15909
 1.01603   2.00873    1.18178
 1.01804   2.00992    1.20446
 1.02005   2.01114    1.22713
 1.02207   2.01237    1.24979
 1.02408   2.01364    1.27244
 ⋮                           
 6.99906  37.0254   382.449  
 7.03627  37.4109   388.516  
 7.07388  37.8025   394.713  
 7.11188  38.2003   401.042  
 7.15028  38.6046   407.508  
 7.18909  39.0153   414.113  
 7.22831  39.4328   420.861  
 7.26795  39.857    427.757  
 7.30803  40.2883   434.805  
 7.34853  40.7267   442.008  
 7.38948  41.1723   449.372  
 7.43088  41.6254   456.899  

Vemos que para este intervalo $t \in [1, 1.8]$ las soluciones se encuentran definidas 😁🎉

<span style="color:magenta"> Intervalo $t \in [1, 1.9]$ <span>

In [22]:
#Método de Euler con Jacobiano analítico
tEulerAnalitico1 = collect(1:0.001:1.9) #paso (0.001) para al menos 4 cifras significativas de t[1,1.9]
solEulerAnalitico1= Euler_mejorado_J_t(EDO_1aumentada,[1.0,2.0,1.0],tEulerAnalitico1,EDO_1_Jacobiano)

901×3 Array{Float64,2}:
   1.0        2.0        1.0    
   1.002      2.00101    1.02276
   1.004      2.00205    1.0455 
   1.006      2.0031     1.06824
   1.00801    2.00418    1.09097
   1.01001    2.00528    1.11369
   1.01202    2.00641    1.1364 
   1.01403    2.00756    1.15909
   1.01603    2.00873    1.18178
   1.01804    2.00992    1.20446
   1.02005    2.01114    1.22713
   1.02207    2.01237    1.24979
   1.02408    2.01364    1.27244
   ⋮                            
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      

Vemos que para este intervalo $t \in [1, 1.9]$ las soluciones no se encuentran definidas ya que nos aparece "NaN"🙁🙁

<span style="color:magenta"> Intervalo $t \in [1, 2.0]$ <span>

In [23]:
#Método de Euler con Jacobiano analítico
tEulerAnalitico2 = collect(1:0.001:2.0) #paso (0.001) para al menos 4 cifras significativas de t[1,2.0]
solEulerAnalitico2= Euler_mejorado_J_t(EDO_1aumentada,[1.0,2.0,1.0],tEulerAnalitico2,EDO_1_Jacobiano)


1001×3 Array{Float64,2}:
   1.0        2.0        1.0    
   1.002      2.00101    1.02276
   1.004      2.00205    1.0455 
   1.006      2.0031     1.06824
   1.00801    2.00418    1.09097
   1.01001    2.00528    1.11369
   1.01202    2.00641    1.1364 
   1.01403    2.00756    1.15909
   1.01603    2.00873    1.18178
   1.01804    2.00992    1.20446
   1.02005    2.01114    1.22713
   1.02207    2.01237    1.24979
   1.02408    2.01364    1.27244
   ⋮                            
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      

Vemos que para este intervalo $t \in [1, 2.0]$ las soluciones no se encuentran definidas ya que nos aparece "NaN"🙁🙁

<span style="color:magenta"> Intervalo $t \in [1, 2.1]$ <span>

In [24]:
#Método de Euler con Jacobiano analítico
tEulerAnalitico3 = collect(1:0.001:2.1) #paso (0.001) para al menos 4 cifras significativas de t[1,2.1]
solEulerAnalitico3= Euler_mejorado_J_t(EDO_1aumentada,[1.0,2.0,1.0],tEulerAnalitico3,EDO_1_Jacobiano)

1101×3 Array{Float64,2}:
   1.0        2.0        1.0    
   1.002      2.00101    1.02276
   1.004      2.00205    1.0455 
   1.006      2.0031     1.06824
   1.00801    2.00418    1.09097
   1.01001    2.00528    1.11369
   1.01202    2.00641    1.1364 
   1.01403    2.00756    1.15909
   1.01603    2.00873    1.18178
   1.01804    2.00992    1.20446
   1.02005    2.01114    1.22713
   1.02207    2.01237    1.24979
   1.02408    2.01364    1.27244
   ⋮                            
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      

Vemos que para este intervalo $t \in [1, 2.1]$ las soluciones no se encuentran definidas ya que nos aparece "NaN"🙁🙁

#### <span style="color:green">Para Euler mejorado con Jacobiano numérico<span>

<span style="color:magenta"> Intervalo $t \in [1, 1.8]$ <span>

In [25]:
#Método de Euler con Jacobiano Numérico
tEulerNumerico = collect(1:0.00001:1.8) #paso(0.00001)para tener al menos 4 cifras significativas de t[1,1.8](Precisión 10^{-4})
solEulerNumerico= Euler_mejorado_J_t_num(EDO_1,EDO_1aumentada,[1.0,2.0,1.0],tEulerNumerico)

80001×3 Array{Float64,2}:
 1.0       2.0        1.0    
 1.00002   2.00001    1.00023
 1.00004   2.00002    1.00046
 1.00006   2.00003    1.00068
 1.00008   2.00004    1.00091
 1.0001    2.00005    1.00114
 1.00012   2.00006    1.00137
 1.00014   2.00007    1.00159
 1.00016   2.00008    1.00182
 1.00018   2.00009    1.00205
 1.0002    2.0001     1.00228
 1.00022   2.00011    1.0025 
 1.00024   2.00012    1.00273
 ⋮                           
 7.42659  41.5793   456.131  
 7.42701  41.5838   456.207  
 7.42742  41.5884   456.283  
 7.42784  41.593    456.359  
 7.42825  41.5975   456.435  
 7.42867  41.6021   456.511  
 7.42908  41.6066   456.587  
 7.4295   41.6112   456.663  
 7.42992  41.6158   456.74   
 7.43033  41.6203   456.816  
 7.43075  41.6249   456.892  
 7.43117  41.6295   456.968  

Vemos que para este intervalo $t \in [1, 1.8]$ las soluciones se encuentran definidas 😁🎉

<span style="color:magenta"> Intervalo $t \in [1, 1.9]$ <span>

In [26]:
#Método de Euler con Jacobiano Numérico
tEulerNumerico1 = collect(1:0.00001:1.9) #paso(0.00001)para tener al menos 4cifras significativas de t[1,1.9](Precisión 10^{-4})
solEulerNumerico1= Euler_mejorado_J_t_num(EDO_1,EDO_1aumentada,[1.0,2.0,1.0],tEulerNumerico1)

90001×3 Array{Float64,2}:
  1.0        2.0         1.0    
  1.00002    2.00001     1.00023
  1.00004    2.00002     1.00046
  1.00006    2.00003     1.00068
  1.00008    2.00004     1.00091
  1.0001     2.00005     1.00114
  1.00012    2.00006     1.00137
  1.00014    2.00007     1.00159
  1.00016    2.00008     1.00182
  1.00018    2.00009     1.00205
  1.0002     2.0001      1.00228
  1.00022    2.00011     1.0025 
  1.00024    2.00012     1.00273
  ⋮                             
 16.7103   208.044    5178.79   
 16.7124   208.095    5180.73   
 16.7145   208.147    5182.67   
 16.7165   208.199    5184.61   
 16.7186   208.251    5186.55   
 16.7207   208.303    5188.49   
 16.7228   208.355    5190.44   
 16.7249   208.407    5192.38   
 16.727    208.459    5194.33   
 16.7291   208.51     5196.28   
 16.7311   208.562    5198.22   
 16.7332   208.614    5200.17   

Vemos que para este intervalo $t \in [1, 1.9]$ las soluciones se encuentran definidas 😁🎉

<span style="color:magenta"> Intervalo $t \in [1, 2.0]$ <span>

In [27]:
#Método de Euler con Jacobiano Numérico
tEulerNumerico2 = collect(1:0.00001:2.0) #paso (0.00001) para al menos 4 cifras significativas de t[1,2.0] (Precisión 10^{-4})
solEulerNumerico2= Euler_mejorado_J_t_num(EDO_1,EDO_1aumentada,[1.0,2.0,1.0],tEulerNumerico2)

100001×3 Array{Float64,2}:
   1.0        2.0        1.0    
   1.00002    2.00001    1.00023
   1.00004    2.00002    1.00046
   1.00006    2.00003    1.00068
   1.00008    2.00004    1.00091
   1.0001     2.00005    1.00114
   1.00012    2.00006    1.00137
   1.00014    2.00007    1.00159
   1.00016    2.00008    1.00182
   1.00018    2.00009    1.00205
   1.0002     2.0001     1.00228
   1.00022    2.00011    1.0025 
   1.00024    2.00012    1.00273
   ⋮                            
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      

Vemos que para este intervalo $t \in [1, 2.0]$ las soluciones no se encuentran definidas ya que nos aparece "NaN"🙁🙁

<span style="color:magenta"> Intervalo $t \in [1, 2.1]$ <span>

In [28]:
#Método de Euler con Jacobiano Numérico
tEulerNumerico3 = collect(1:0.00001:2.1) #paso (0.00001) para tener al menos 4 cifras significativas de t[1,2.1](Precisión 10^{-4})
solEulerNumerico3= Euler_mejorado_J_t_num(EDO_1,EDO_1aumentada,[1.0,2.0,1.0],tEulerNumerico3)

110001×3 Array{Float64,2}:
   1.0        2.0        1.0    
   1.00002    2.00001    1.00023
   1.00004    2.00002    1.00046
   1.00006    2.00003    1.00068
   1.00008    2.00004    1.00091
   1.0001     2.00005    1.00114
   1.00012    2.00006    1.00137
   1.00014    2.00007    1.00159
   1.00016    2.00008    1.00182
   1.00018    2.00009    1.00205
   1.0002     2.0001     1.00228
   1.00022    2.00011    1.0025 
   1.00024    2.00012    1.00273
   ⋮                            
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      
 NaN        NaN        NaN      

Vemos que para este intervalo $t \in [1, 2.1]$ las soluciones no se encuentran definidas ya que nos aparece "NaN"🙁🙁

#### <span style="color:green">Para Runge-Kutta de $2^{\circ}$ orden<span>

<span style="color:magenta"> Intervalo $t \in [1, 1.8]$ <span>

In [29]:
#Método de Runge-Kutta de 2do orden
tRK2do = collect(1:0.0001:1.8) #paso (0.0001) para tener al menos 4 cifras significativas de t[1,1.8](Precisión 10^{-4})
solRK2do = RK_2(EDO_1,[1.0,2.0,1.0],tRK2do)

8001×3 Array{Float64,2}:
 1.0       2.0        1.0    
 1.0002    2.0001     1.00228
 1.0004    2.0002     1.00455
 1.0006    2.0003     1.00683
 1.0008    2.0004     1.0091 
 1.001     2.0005     1.01138
 1.0012    2.0006     1.01365
 1.0014    2.00071    1.01593
 1.0016    2.00081    1.01821
 1.0018    2.00091    1.02048
 1.002     2.00101    1.02276
 1.0022    2.00111    1.02503
 1.0024    2.00122    1.02731
 ⋮                           
 7.38565  41.1314   448.694  
 7.38976  41.1763   449.438  
 7.39388  41.2212   450.183  
 7.39801  41.2663   450.93   
 7.40213  41.3114   451.679  
 7.40627  41.3566   452.43   
 7.41041  41.4019   453.182  
 7.41455  41.4473   453.935  
 7.41869  41.4927   454.691  
 7.42285  41.5382   455.448  
 7.427    41.5838   456.207  
 7.43116  41.6295   456.967  

Vemos que para este intervalo $t \in [1, 1.8]$ las soluciones se encuentran definidas 😁🎉

<span style="color:magenta"> Intervalo $t \in [1, 1.9]$ <span>

In [30]:
#Método de Runge-Kutta de 2do orden
tRK2do1 = collect(1:0.0001:1.9) #paso (0.0001) para tener al menos 4 cifras significativas de t[1,1.9](Precisión 10^{-4})
solRK2do1 = RK_2(EDO_1,[1.0,2.0,1.0],tRK2do1)

9001×3 Array{Float64,2}:
  1.0       2.0         1.0    
  1.0002    2.0001      1.00228
  1.0004    2.0002      1.00455
  1.0006    2.0003      1.00683
  1.0008    2.0004      1.0091 
  1.001     2.0005      1.01138
  1.0012    2.0006      1.01365
  1.0014    2.00071     1.01593
  1.0016    2.00081     1.01821
  1.0018    2.00091     1.02048
  1.002     2.00101     1.02276
  1.0022    2.00111     1.02503
  1.0024    2.00122     1.02731
  ⋮                            
 16.5068  203.009    4991.51   
 16.5271  203.509    5010.01   
 16.5475  204.011    5028.6    
 16.5679  204.515    5047.29   
 16.5884  205.021    5066.06   
 16.6089  205.528    5084.93   
 16.6295  206.038    5103.89   
 16.6502  206.549    5122.95   
 16.6708  207.062    5142.11   
 16.6916  207.577    5161.35   
 16.7124  208.094    5180.7    
 16.7332  208.613    5200.14   

Vemos que para este intervalo $t \in [1, 1.9]$ las soluciones se encuentran definidas 😁🎉 

<span style="color:magenta"> Intervalo $t \in [1, 2.0]$ <span>

In [31]:
#Método de Runge-Kutta de 2do orden
tRK2do2 = collect(1:0.0001:2.0) #paso (0.0001) para tener al menos 4 cifras significativas de t[1,2.0](Precisión 10^{-4})
solRK2do2 = RK_2(EDO_1,[1.0,2.0,1.0],tRK2do2)

DomainError: DomainError with -Inf:
cos(x) is only defined for finite x.

Vemos que para este intervalo $t \in [1, 2.0]$ las soluciones no se encuentran definidas ya que nos aparece "error"🙁🙁

<span style="color:magenta"> Intervalo $t \in [1, 2.1]$ <span>

In [32]:
#Método de Runge-Kutta de 2do orden
tRK2do3 = collect(1:0.0001:2.1) #paso (0.0001) para tener al menos 4 cifras significativas de t[1,2.1](Precisión 10^{-4})
solRK2do3 = RK_2(EDO_1,[1.0,2.0,1.0],tRK2do3)

DomainError: DomainError with -Inf:
cos(x) is only defined for finite x.

Vemos que para este intervalo $t \in [1, 2.1]$ las soluciones no se encuentran definidas ya que nos aparece "error"🙁🙁

#### <span style="color:green">Para Runge-Kutta de $4^{\circ}$ orden<span>

<span style="color:magenta"> Intervalo $t \in [1, 1.8]$ <span>

In [33]:
#Método de Runge-Kutta de 4to orden
tRK4to = collect(1:0.0001:1.8) #paso (0.0001) para tener al menos 4 cifras significativas de t[1,1.8](Precisión 10^{-4})
solRK4to = RK_4(EDO_1,[1.0,2.0,1.0],tRK4to)

8001×3 Array{Float64,2}:
 1.0       2.0        1.0    
 1.0002    2.0001     1.00228
 1.0004    2.0002     1.00455
 1.0006    2.0003     1.00683
 1.0008    2.0004     1.0091 
 1.001     2.0005     1.01138
 1.0012    2.0006     1.01365
 1.0014    2.00071    1.01593
 1.0016    2.00081    1.01821
 1.0018    2.00091    1.02048
 1.002     2.00101    1.02276
 1.0022    2.00111    1.02503
 1.0024    2.00122    1.02731
 ⋮                           
 7.38565  41.1314   448.694  
 7.38976  41.1763   449.438  
 7.39388  41.2213   450.184  
 7.39801  41.2663   450.931  
 7.40214  41.3115   451.68   
 7.40627  41.3567   452.43   
 7.41041  41.402    453.182  
 7.41455  41.4473   453.936  
 7.4187   41.4927   454.691  
 7.42285  41.5382   455.449  
 7.42701  41.5838   456.207  
 7.43117  41.6295   456.968  

Vemos que para este intervalo $t \in [1, 1.8]$ las soluciones se encuentran definidas 😁🎉

<span style="color:magenta"> Intervalo $t \in [1, 1.9]$ <span>

In [34]:
#Método de Runge-Kutta de 4to orden
tRK4to1 = collect(1:0.0001:1.9) #paso (0.0001) para tener al menos 4 cifras significativas de t[1,1.9](Precisión 10^{-4})
solRK4to1 = RK_4(EDO_1,[1.0,2.0,1.0],tRK4to1)

9001×3 Array{Float64,2}:
  1.0       2.0         1.0    
  1.0002    2.0001      1.00228
  1.0004    2.0002      1.00455
  1.0006    2.0003      1.00683
  1.0008    2.0004      1.0091 
  1.001     2.0005      1.01138
  1.0012    2.0006      1.01365
  1.0014    2.00071     1.01593
  1.0016    2.00081     1.01821
  1.0018    2.00091     1.02048
  1.002     2.00101     1.02276
  1.0022    2.00111     1.02503
  1.0024    2.00122     1.02731
  ⋮                            
 16.5068  203.01     4991.54   
 16.5272  203.51     5010.04   
 16.5476  204.012    5028.63   
 16.568   204.516    5047.31   
 16.5885  205.022    5066.09   
 16.609   205.529    5084.96   
 16.6296  206.039    5103.92   
 16.6502  206.55     5122.98   
 16.6709  207.063    5142.13   
 16.6916  207.578    5161.38   
 16.7124  208.095    5180.73   
 16.7332  208.614    5200.17   

Vemos que para este intervalo $t \in [1, 1.9]$ las soluciones se encuentran definidas 😁🎉

<span style="color:magenta"> Intervalo $t \in [1, 2.0]$ <span>

In [35]:
#Método de Runge-Kutta de 4to orden
tRK4to2 = collect(1:0.0001:2.0) #paso (0.0001) para tener al menos 4 cifras significativas de t[1,2.0](Precisión 10^{-4})
solRK4to2 = RK_4(EDO_1,[1.0,2.0,1.0],tRK4to2)

DomainError: DomainError with -Inf:
cos(x) is only defined for finite x.

Vemos que para este intervalo $t \in [1, 2.0]$ las soluciones no se encuentran definidas ya que nos aparece "error"🙁🙁

<span style="color:magenta"> Intervalo $t \in [1, 2.1]$ <span>

In [36]:
#Método de Runge-Kutta de 4to orden
tRK4to3 = collect(1:0.0001:2.1) #paso (0.0001) para tener al menos 4 cifras significativas de t[1,2.1](Precisión 10^{-4})
solRK4to3 = RK_4(EDO_1,[1.0,2.0,1.0],tRK4to3)

DomainError: DomainError with -Inf:
cos(x) is only defined for finite x.

Vemos que para este intervalo $t \in [1, 2.1]$ las soluciones no se encuentran definidas ya que nos aparece "error"🙁🙁

Podemos ver que los métodos no se encuentran definidos a partir de cierto intervalo de $t$:
1. Euler mejorado con Jacobiano analítico no se encuentra definida apartir del intervalo $t \in [1, 1.9]$
2. Euler mejorado con Jacobiano numérico no se encuentra definida apartir del intervalo $t \in [1, 2.0]$
3. Runge-Kutta de  $2^{\circ}$  orden no se encuentra definida apartir del intervalo $t \in [1, 2.0]$
4. Runge-Kutta de  $4^{\circ}$  orden no se encuentra definida apartir del intervalo $t \in [1, 2.0]$

#### <span style="color:brown">Pasos de integración que proporcionan una precisión de $10^{−4}$ en cada método:<span>
1. Euler mejorado con Jacobiano analítico pasos de $0.001$
2. Euler mejorado con Jacobiano numérico pasos de $0.00001$
3. Runge-Kutta de  $2^{\circ}$  orden pasos de $0.0001$
4. Runge-Kutta de  $4^{\circ}$  orden pasos de $0.0001$

Si gráficamos la solución para los Métodos empleados el Método de RK de orden 4 y el Método de Euler mejorado con Jacobiano analítico tenemos:

<span style="color:blue">3. Modifique las funciones integradoras que programamos en clase (Euler mejorado, Runge-Kutta de $2\circ$ orden y Runge-Kutta de $4\circ$ orden) para que se puedan pasar argumentos opcionales al sistema de ecuaciones diferenciales de tal manera que se puedan modificar parámetros al momento de hacer la integración. Una vez hecho esto, obtenga la solución de la siguiente ecuación diferencial
    \begin{equation}
    \ddot{x}+\frac{1}{10}\dot{x}+4\sin x=\frac{1}{2}\sin(\omega t) 
    \end{equation}
    Con condiciones iniciales $\dot{x}(0)=1$ y $x(0)=0$ y para $\omega=\{1,1.1,1.2,1.3,...,2.9,3\}$. Realice la gráfica de algunas soluciones que representen el comportamiento de la solución en función de $\omega$ y explique su resultado. La solución debe tener una precisión de por lo menos $10^{-5}$.<span>

Si escribimos la ecuación diferencial como un sistema de ecuaciones tal como hicimos en el problema 2 tenemos:

\begin{equation}
\begin{aligned}
x&=x_1\\
\dot{x}_1 &= x_2\\
\dot{x}_2 &= -\frac{1}{10}x_2 - 4\sin{(x_1)} + \frac{1}{2}\sin{(\omega t)}
\end{aligned}
\end{equation}

Al igual que el ejercicio 2 definimos una función con el sistema de ecuaciones "EDO_2"

In [43]:
function EDO_2(vec,t,ω)
     # donde "vec = [x1, x2]"
    dx1 = vec[2]
    dx2 = -vec[2]/10 - 4*sin(vec[1]) + 0.5*sin(ω*t)
    return [dx1,dx2,1.0] #Agregamos 1.0 en la última entrada
end

EDO_2 (generic function with 1 method)

Definimos una funcion para su Jacobiano Analítco "EDO_2_Jacobiano"

In [44]:
function EDO_2_Jacobiano(vec,t,ω) #donde "vec=[x1,x2]",param = [ omega ] y ω = param
    J = zeros(length(vec),length(vec)+1)
    J[1,2] = 1.0
    J[2,1] = -4*cos(vec[1])
    J[2,2] = -1/10
    J[2,3] = 0.5*ω*cos(ω*t)
    return J
end

EDO_2_Jacobiano (generic function with 1 method)

Usaremos la funciones para el Método de Euler mejorado visto en el Notebook 9 pero modificandolo (agregando $\omega$ y cambiando algunas líneas):

In [45]:
function Euler_mejorado_con_omega(edo,p_ini,t,jacob,ω)  
    # J y g con dependencia temporal con parámetros externos
    sol = zeros(length(t),length(p_ini))
    sol[1,:] = p_ini
    δ = t[2]-t[1]
    for i in 1:(length(t)-1)
        #cambiamos a "eval" para que dependa de w, literal solo lo agregamos con ",ω"😅
        eval_edo = edo(sol[i,:],t[i],ω)
        if length(eval_edo) == length(p_ini)
            sol[i+1,:] .= sol[i,:] .+ δ .*eval_edo
        else
            sol[i+1,:] .= sol[i,:] .+ δ .*eval_edo[1:(end-1)]
        end
        sol[i+1,:] .+= 0.5*(δ^2) .*(jacob(sol[i,:],t[i],ω) *eval_edo ) # igual solo lo agregamos con ",ω"😅
    end
    return sol
end

Euler_mejorado_con_omega (generic function with 1 method)

Definimos otra función con la ecuación que vamos a usar para los Métodos RK2 Y RK4

In [46]:
#Es básicamento "EDO_2" pero sin la entrada de "1.0"
function EDO_2_1(vec,t,ω)
    # "vec = [x1, x2]"
    dx1 = vec[2]
    dx2 = -vec[2]/10 - 4*sin(vec[1]) + 0.5*sin(ω*t)
    return [dx1,dx2]
end

EDO_2_1 (generic function with 1 method)

Usamos la función "RK_2" que copiamos tal cual esta en el Notebook 10 pero agregando un param "$\omega$"

In [47]:
#Copiamos tal cual esta en el Notebook 10 😅 pero agregando omega
function RK_2_con_omega(edo,x_ini,t,ω)
    sol = zeros( length(t) , length(x_ini) )
    sol[1,:] .= x_ini
    δ = t[2]-t[1]
    for i in 1:length(t)-1
        k1 = sol[i,:] .+ 0.5*δ .*edo(sol[i,:],t[i],ω)       #literal solo lo agregamos con ",ω"😅
        sol[i+1,:] .= sol[i,:] .+ δ*edo(k1,t[i]+0.5*δ,ω)
    end
    return sol
end

RK_2_con_omega (generic function with 1 method)

Usamos la función "RK_2" que copiamos tal cual esta en el Notebook 10 pero agregando un param "$\omega$"

In [48]:
#Copiamos tal cual esta en el Notebook 10 😅 pero agregando omega
function RK_4_con_omega(edo,x_ini,t,ω)
    sol = zeros( length(t) , length(x_ini) )
    sol[1,:] .= x_ini
    δ = t[2]-t[1]
    for i in 1:length(t)-1
        k1 = edo(sol[i,:],t[i],ω)
        k2 = edo(sol[i,:] .+ 0.5*δ.*k1 , t[i] + 0.5*δ,ω)   #literal solo lo agregamos con ",ω"😅
        k3 = edo(sol[i,:] .+ 0.5*δ.*k2 , t[i] + 0.5*δ,ω)
        k4 = edo(sol[i,:] .+ δ.*k2 , t[i] + δ,ω)
        sol[i+1,:] .= sol[i,:] .+ (δ/6.0).*(k1 .+ 2.0.*k2 .+ 2.0.*k3 .+ k4)
    end
    return sol
end

RK_4_con_omega (generic function with 1 method)

Utilizaremos los diferentes métodos de integración para encontrar un paso de integración que proporcione una precisión de $10^{−5}$ tomando a $\omega=cte$ una vez que encontremos el paso de integración es cuando vamos a variar $\omega$ 

#### <span style="color:green">Para Euler mejorado <span>

In [49]:
#Método de Euler Mejorado
tEprueba = collect(0:0.01:10π)
solucionE = Euler_mejorado_con_omega(EDO_2,[0.0,1.0],tEprueba,EDO_2_Jacobiano,1.1)

3142×2 Array{Float64,2}:
  0.0         1.0      
  0.009995    0.998828 
  0.0199766   0.997313 
  0.0299413   0.995455 
  0.0398857   0.993257 
  0.0498064   0.990719 
  0.0597001   0.987842 
  0.0695633   0.984629 
  0.0793926   0.981082 
  0.0891849   0.977201 
  0.0989367   0.97299  
  0.108645    0.968451 
  0.118306    0.963586 
  ⋮                    
 -0.0226856  -0.0640721
 -0.0233183  -0.0624801
 -0.0239352  -0.0609193
 -0.0245367  -0.0593904
 -0.025123   -0.057894 
 -0.0256946  -0.0564307
 -0.0262517  -0.0550012
 -0.0267946  -0.053606 
 -0.0273238  -0.0522457
 -0.0278395  -0.0509208
 -0.0283422  -0.0496319
 -0.0288322  -0.0483793

Vemos que el paso "0.01" nos da una precisión de al menos $10^{-5}$ 

#### <span style="color:green">Para Runge-Kutta de $2^{\circ}$ orden<span>

In [50]:
#Método de Runge-Kutta de 2do orden
tRK2prueba = collect(0:0.01:10π)
solucionRK2 = RK_2_con_omega(EDO_2_1,[0.0,1.0],tRK2prueba,1.1)

3142×2 Array{Float64,2}:
  0.0         1.0      
  0.009995    0.998828 
  0.0199766   0.997313 
  0.0299413   0.995455 
  0.0398857   0.993257 
  0.0498064   0.990719 
  0.0597001   0.987842 
  0.0695633   0.98463  
  0.0793926   0.981082 
  0.0891849   0.977202 
  0.0989367   0.972991 
  0.108645    0.968451 
  0.118306    0.963586 
  ⋮                    
 -0.0226877  -0.0640709
 -0.0233204  -0.0624788
 -0.0239373  -0.060918 
 -0.0245387  -0.059389 
 -0.0251251  -0.0578925
 -0.0256966  -0.0564292
 -0.0262537  -0.0549996
 -0.0267966  -0.0536043
 -0.0273257  -0.052244 
 -0.0278415  -0.050919 
 -0.0283441  -0.0496299
 -0.0288341  -0.0483773

Vemos que el paso "0.01" nos da una precisión de al menos $10^{-5}$ 

#### <span style="color:green">Para Runge-Kutta de $4^{\circ}$ orden<span>

In [51]:
#Método de Runge-Kutta de 4to orden
tRK4prueba = collect(0:0.01:10π)
solucionRK4 = RK_4_con_omega(EDO_2_1,[0.0,1.0],tRK4prueba,1.1)

3142×2 Array{Float64,2}:
  0.0          1.0      
  0.00999443   0.998828 
  0.0199754    0.997313 
  0.0299395    0.995456 
  0.0398834    0.993258 
  0.0498036    0.99072  
  0.0596967    0.987844 
  0.0695593    0.984631 
  0.0793882    0.981084 
  0.0891799    0.977204 
  0.0989312    0.972994 
  0.108639     0.968455 
  0.118299     0.963591 
  ⋮                     
 -0.0229618   -0.0644734
 -0.0235985   -0.06287  
 -0.0242193   -0.0612976
 -0.0248246   -0.059757 
 -0.0254146   -0.0582488
 -0.0259896   -0.0567736
 -0.0265501   -0.055332 
 -0.0270964   -0.0539245
 -0.0276287   -0.0525519
 -0.0281475   -0.0512145
 -0.0286532   -0.0499129
 -0.0291459   -0.0486477

Vemos que el paso "0.01" nos da una precisión de al menos $10^{-5}$ 

<span style="color:brown">Vemos que tEprueba = tRK2prueba = tRK4prueba = collect(0:0.01:10π) por lo que el paso $0.01$ nos da una precisión de al menos $10^{-5}$ por lo que podemos definir una t general para usar en cualquiera de los métodos:<span>

In [52]:
t=collect(0:0.01:10π) #t general
#Ya que tenemos el paso de integración con el que tenemos la precisión que se pide podemos encontrar las soluciones 
#para las diferentes omegas
omegas = collect(1:0.1:3)
plot(title="Solución para x_1 con diversos valores de ω usando Euler",xlabel="t",ylabel="x(t)")
for ω in omegas
    solucion1 = Euler_mejorado_con_omega(EDO_2,[0.0,1.0],t,EDO_2_Jacobiano,ω)
    plot!(t,solucion1[:,1],label ="ω=$(ω)", lw=1.0)
end
plot!()

UndefVarError: UndefVarError: plot not defined

Veamos ahora las soluciones para $x_2$.

In [53]:
plot(title="Solución para x_2 con diversos valores de ω usando Euler",xlabel="t",ylabel="x(t)")
for ω in omegas
    solucion2 = Euler_mejorado__con_omega(EDO2,[0.0,1.0],t,EDO_2_Jacobiano,ω)
    plot!(t,solucion2[:,2],label ="ω=$(ω)", lw=1.0)
end
plot!()

UndefVarError: UndefVarError: plot not defined

Ahora obtengamos las soluciones para $x_1$ y $x_2$ con los metodos de Rugen-Kutta.

In [54]:
plot(title="Solución para x_1 con diversos valores de ω usando RK_2",xlabel="t",ylabel="x(t)")
for ω in omegas
    solucion3 = RK_2__con_omega(EDO_2_1,[0.0,1.0],t,ω)
    plot!(t,solucion3[:,1],label ="ω=$(ω)", lw=1.0)
end
plot!()

UndefVarError: UndefVarError: plot not defined

In [55]:
plot(title="Solución para x_2 con diversos valores de ω usando RK_2",xlabel="t",ylabel="x(t)")
for ω in omegas
    solucion4 = RK_2_con_omega(EDO2_1,[0.0,1.0],t,ω)
    plot!(t,solucion4[:,2],label ="ω=$(ω)", lw=1.0)
end
plot!()

UndefVarError: UndefVarError: plot not defined

Realicemos el mismo procedimiento para el método de Rugen-Kutta de 4to orden.

In [56]:
plot(title="Solución para x_1 con diversos valores de ω usando RK_4",xlabel="t",ylabel="x(t)")
for ω in omegas
    solucion5 = RK_4__con_omega(EDO2_1,[0.0,1.0],t,ω)
    plot!(t,solucion5[:,1],label ="ω=$(ω)", lw=1.0)
end
plot!()

UndefVarError: UndefVarError: plot not defined

In [57]:
plot(title="Solución para x_1 con diversos valores de ω usando RK_4",xlabel="t",ylabel="x(t)")
for ω in omegas
    solucion6 = RK_4_con_omega(EDO2_1,[0.0,1.0],t,ω)
    plot!(t,solucion6[:,2],label ="ω=$(ω)", lw=1.0)
end
plot!()

UndefVarError: UndefVarError: plot not defined

-Conclusiones-

<span style="color:blue">4. Considere el siguiente sistema de ecuaciones diferenciales 
\begin{equation}
\begin{aligned}
\frac{dx}{dt}&=10(y-x)\\
\frac{dx}{dt}&=x(28-z)-y\\
\frac{dx}{dt}&=xy-\frac{8}{3}z
\end{aligned}
\end{equation}
Realice una integración numérica del sistema de ecuaciones con el método de Runge-Kutta de $4\circ$ y realice los siguientes ejercicios:<span>
    
<span style="color:blue">(a) Elija una condición inicial aleatoria en el $x,y,z \in [-5,5]$ y realice la gráfica de la solución en el plano $xy$, $xz$ y $yz$ y comente sus observaciones.<span>
    
<span style="color:blue">(b) Ahora tome 3 soluciones parecidas. Para ello proponga 3 condicioness iniciales tales que en la coordenada en $y$ las condiciones inciales difieran entre si en $10^{-2}$. Explique lo que observa.<span>
    
<span style="color:blue">Nota: De preferencia realice integraciones con tiempos relativamente largos en los que pueda apreciar diferencias en el comportamiento de las soluciones. Además asegure que cada una de las soluciones que encuentre sea convergente en por lo menos 5 cifras (10^{-5}), es decir encuentre un paso adecuado para realizar la integración. <span>


Al igual que el ejercicio 2 y 3 definimos una función con el sistema de ecuaciones "EDO_3"

In [10]:
function EDO_3(vec,t)
    # donde "vec = [x1, x2, x3]""
    dx = 10*vec[2] - 10*vec[1]
    dy = 28*vec[1] - vec[1]*vec[3] - vec[2]
    dz = vec[1]*vec[2] - 8*vec[3]/3
    return [dx,dy,dz]
end

EDO_3 (generic function with 1 method)

El inciso a) nos pide que elijamos una condición aleatroria en el $x,y,z \in [-5,5]$ por lo que usaremos "rand()" para escoger un número aleatorio de cero a uno y que se multiplique por 5 o -5.

In [2]:
#Obtención de la condición inicial.
vec0=[5rand(),-5rand(),5rand()]

3-element Array{Float64,1}:
  2.8444813962693827
 -1.8970707930859265
  3.644156233315342 

#### <span style="color:green"> Gráficamos las soluciones para los diferentes planos <span>

##### <span style="color:magenta">Plano xy<span> 

In [6]:
#Graficamos la solución en el plano xy usando las condiciones iniciales:
t2 = collect(0:0.01:300)
solucion7 = RK_4(EDO_3,vec0,t2) #vec0 son las condiciones inciales aleatorias
plot(title="Solución-plano xy",xlabel="x(t)",ylabel="y(t)")
plot!(solucion7[:,1],solucion7[:,2])
plot!(legend=false)

UndefVarError: UndefVarError: plot not defined

##### <span style="color:magenta">Plano yz<span> 

In [8]:
plot(title="Espacio Fase-plano yz",xlabel="y(t)",ylabel="z(t)")
plot!(solucion7[:,2],solucion7[:,3])
plot!(legend=false)

UndefVarError: UndefVarError: plot not defined

##### <span style="color:magenta">Plano xz<span> 

In [7]:
plot(title="Solución-plano xz",xlabel="x(t)",ylabel="z(t)")
plot!(solucion7[:,1],solucion7[:,3])
plot!(legend=false)

UndefVarError: UndefVarError: plot not defined

El inciso b) nos pide que tomemos 3 soluciones parecidas por lo que vamos a proponer 3 condiciones iniciales tales que en la coordenada en $y$ las condiciones inciales difieran entre si en $10^{-2}$. Vamos a utilizar las condiciones aleatorias "vec0" 

#### <span style="color:green"> Primer condición inicial <span>

In [14]:
vec0_1=[vec0[1]+0.1,vec0[2]+0.001,vec0[3]-0.1] #con esto estamos pidiendo que difieran en 10^{-2}
t3 = collect(0:0.001:100)
solucion8_1 = RK_4(EDO_3,vec0_2,t3)

100001×3 Array{Float64,2}:
  2.74448  -1.89607   3.64416
  2.69865  -1.82791   3.62939
  2.65394  -1.76087   3.61493
  2.61034  -1.69494   3.60076
  2.56783  -1.63009   3.58687
  2.52638  -1.5663    3.57326
  2.48597  -1.50353   3.5599 
  2.44658  -1.44177   3.54679
  2.4082   -1.38098   3.53392
  2.37079  -1.32116   3.52129
  2.33435  -1.26227   3.50888
  2.29885  -1.20428   3.49668
  2.26428  -1.14719   3.48469
  ⋮                          
 -4.27859  -6.8056   16.5626 
 -4.30394  -6.84788  16.5477 
 -4.32947  -6.89048  16.5333 
 -4.35516  -6.93339  16.5192 
 -4.38103  -6.97662  16.5056 
 -4.40707  -7.02015  16.4923 
 -4.43329  -7.06401  16.4795 
 -4.45969  -7.10817  16.4671 
 -4.48626  -7.15266  16.4551 
 -4.51302  -7.19745  16.4435 
 -4.53995  -7.24257  16.4323 
 -4.56707  -7.288    16.4216 

#### <span style="color:green"> Segunda condición inicial <span>

In [12]:
vec0_2=[vec0[1]-0.1,vec0[2]+0.001,vec0[3]]
t3_2 = collect(0:0.001:100)
solucion8_2 = RK_4(EDO_3,vec0_2,t3_2)

100001×3 Array{Float64,2}:
  2.74448  -1.89607   3.64416
  2.69865  -1.82791   3.62939
  2.65394  -1.76087   3.61493
  2.61034  -1.69494   3.60076
  2.56783  -1.63009   3.58687
  2.52638  -1.5663    3.57326
  2.48597  -1.50353   3.5599 
  2.44658  -1.44177   3.54679
  2.4082   -1.38098   3.53392
  2.37079  -1.32116   3.52129
  2.33435  -1.26227   3.50888
  2.29885  -1.20428   3.49668
  2.26428  -1.14719   3.48469
  ⋮                          
 -4.27859  -6.8056   16.5626 
 -4.30394  -6.84788  16.5477 
 -4.32947  -6.89048  16.5333 
 -4.35516  -6.93339  16.5192 
 -4.38103  -6.97662  16.5056 
 -4.40707  -7.02015  16.4923 
 -4.43329  -7.06401  16.4795 
 -4.45969  -7.10817  16.4671 
 -4.48626  -7.15266  16.4551 
 -4.51302  -7.19745  16.4435 
 -4.53995  -7.24257  16.4323 
 -4.56707  -7.288    16.4216 

#### <span style="color:green"> Tercer condición inicial <span>

In [13]:
vec0_3=[vec0[1]+0.2,vec0[2]+0.003,vec0[3]+0.01]
t3_3 = collect(0:0.01:100)
solucion8_3= RK_4(EDO_3,vec0_3,t3_3)

10001×3 Array{Float64,2}:
   3.04448   -1.89407     3.65416
   2.60918   -1.19058     3.51512
   2.27741   -0.583828    3.40131
   2.03125   -0.0511424   3.30508
   1.85643    0.426589    3.22171
   1.74174    0.865523    3.14839
   1.67844    1.27943     3.08361
   1.65985    1.6802      3.0268 
   1.68096    2.07825     2.97809
   1.73821    2.4829      2.93815
   1.82919    2.90264     2.90818
   1.95251    3.34541     2.88989
   2.10766    3.81879     2.88554
   ⋮                             
  -5.34809   -9.66606    11.6167 
  -5.79755  -10.4713     11.8647 
  -6.28331  -11.3267     12.2021 
  -6.80654  -12.2284     12.6417 
  -7.36779  -13.1703     13.1973 
  -7.96682  -14.1425     13.8836 
  -8.6023   -15.1314     14.7153 
  -9.2715   -16.1184     15.7067 
  -9.96992  -17.0796     16.8703 
 -10.6909   -17.9852     18.2151 
 -11.4253   -18.7993     19.7447 
 -12.1613   -19.4811     21.4553 

#### <span style="color:magenta"> Gráficamos para comparar las soluciones <span>

In [15]:
plot(title="Solución en el plano xy",xlabel="x(t)",ylabel="y(t)")
plot!(solucion8_1[:,1],solucion8_1[:,2],label ="Condición inicial1")
plot!(solucion8_2[:,1],solucion8_2[:,2],label ="Condición inicial2")
plot!(solucion8_3[:,1],solucion8_3[:,2],label="Condición inicial3")
plot!()

UndefVarError: UndefVarError: plot not defined

In [16]:
plot(title="Solución en el plano plano yz",xlabel="y(t)",ylabel="z(t)")
plot!(solucion8_1[:,2],solucion8_1[:,3],label="Condición inicial1")
plot!(solucion8_2[:,2],solucion8_2[:,3],label="Condición inicial2")
plot!(solucion8_3[:,2],solucion8_3[:,3],label="Condición inicial3")
plot!()

UndefVarError: UndefVarError: plot not defined

In [17]:
plot(title="Solución en el plano plano xz",xlabel="x(t)",ylabel="z(t)")
plot!(solucion4b_1[:,1],solucion8_1[:,3],label="Condición inicial1")
plot!(solucion4b_2[:,1],solucion8_2[:,3],label="Condición inicial2")
plot!(solucion4b_3[:,1],solucion8_3[:,3],label="Condición inicial")
plot!()

UndefVarError: UndefVarError: plot not defined